#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.34209
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinalProject.DataLINQ
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="ProyectoFinal")]
	public partial class BDLINQDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Definiciones de métodos de extensibilidad
    partial void OnCreated();
    partial void InsertUsuarios(Usuarios instance);
    partial void UpdateUsuarios(Usuarios instance);
    partial void DeleteUsuarios(Usuarios instance);
    partial void InsertPuntuaciones(Puntuaciones instance);
    partial void UpdatePuntuaciones(Puntuaciones instance);
    partial void DeletePuntuaciones(Puntuaciones instance);
    partial void InsertPerfil(Perfil instance);
    partial void UpdatePerfil(Perfil instance);
    partial void DeletePerfil(Perfil instance);
    partial void InsertLugar(Lugar instance);
    partial void UpdateLugar(Lugar instance);
    partial void DeleteLugar(Lugar instance);
    partial void InsertJuegos(Juegos instance);
    partial void UpdateJuegos(Juegos instance);
    partial void DeleteJuegos(Juegos instance);
    #endregion
		
		public BDLINQDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["ProyectoFinalConnectionString1"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public BDLINQDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public BDLINQDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public BDLINQDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public BDLINQDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Usuarios> Usuarios
		{
			get
			{
				return this.GetTable<Usuarios>();
			}
		}
		
		public System.Data.Linq.Table<PuntuacionUsuario> PuntuacionUsuario
		{
			get
			{
				return this.GetTable<PuntuacionUsuario>();
			}
		}
		
		public System.Data.Linq.Table<Puntuaciones> Puntuaciones
		{
			get
			{
				return this.GetTable<Puntuaciones>();
			}
		}
		
		public System.Data.Linq.Table<Perfil> Perfil
		{
			get
			{
				return this.GetTable<Perfil>();
			}
		}
		
		public System.Data.Linq.Table<Lugar> Lugar
		{
			get
			{
				return this.GetTable<Lugar>();
			}
		}
		
		public System.Data.Linq.Table<Juegos> Juegos
		{
			get
			{
				return this.GetTable<Juegos>();
			}
		}
		
		public System.Data.Linq.Table<seguidores> seguidores
		{
			get
			{
				return this.GetTable<seguidores>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Usuarios")]
	public partial class Usuarios : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _Nick;
		
		private string _Nombre;
		
		private string _Apellidos;
		
		private System.Data.Linq.Binary _Contraseña;
		
		private string _Correo;
		
		private System.Nullable<System.DateTime> _FechaNacimiento;
		
		private System.DateTime _FechaInicio;
		
		private int _Perfil;
		
		private System.Nullable<int> _ID_Residencia;
		
		private bool _EstadoCuenta;
		
		private EntityRef<Perfil> _Perfil1;
		
		private EntityRef<Lugar> _Lugar;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnNickChanging(string value);
    partial void OnNickChanged();
    partial void OnNombreChanging(string value);
    partial void OnNombreChanged();
    partial void OnApellidosChanging(string value);
    partial void OnApellidosChanged();
    partial void OnContraseñaChanging(System.Data.Linq.Binary value);
    partial void OnContraseñaChanged();
    partial void OnCorreoChanging(string value);
    partial void OnCorreoChanged();
    partial void OnFechaNacimientoChanging(System.Nullable<System.DateTime> value);
    partial void OnFechaNacimientoChanged();
    partial void OnFechaInicioChanging(System.DateTime value);
    partial void OnFechaInicioChanged();
    partial void OnPerfilChanging(int value);
    partial void OnPerfilChanged();
    partial void OnID_ResidenciaChanging(System.Nullable<int> value);
    partial void OnID_ResidenciaChanged();
    partial void OnEstadoCuentaChanging(bool value);
    partial void OnEstadoCuentaChanged();
    #endregion
		
		public Usuarios()
		{
			this._Perfil1 = default(EntityRef<Perfil>);
			this._Lugar = default(EntityRef<Lugar>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nick", DbType="VarChar(30) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string Nick
		{
			get
			{
				return this._Nick;
			}
			set
			{
				if ((this._Nick != value))
				{
					this.OnNickChanging(value);
					this.SendPropertyChanging();
					this._Nick = value;
					this.SendPropertyChanged("Nick");
					this.OnNickChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nombre", DbType="VarChar(40) NOT NULL", CanBeNull=false)]
		public string Nombre
		{
			get
			{
				return this._Nombre;
			}
			set
			{
				if ((this._Nombre != value))
				{
					this.OnNombreChanging(value);
					this.SendPropertyChanging();
					this._Nombre = value;
					this.SendPropertyChanged("Nombre");
					this.OnNombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Apellidos", DbType="VarChar(80) NOT NULL", CanBeNull=false)]
		public string Apellidos
		{
			get
			{
				return this._Apellidos;
			}
			set
			{
				if ((this._Apellidos != value))
				{
					this.OnApellidosChanging(value);
					this.SendPropertyChanging();
					this._Apellidos = value;
					this.SendPropertyChanged("Apellidos");
					this.OnApellidosChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Contraseña", DbType="VarBinary(255) NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public System.Data.Linq.Binary Contraseña
		{
			get
			{
				return this._Contraseña;
			}
			set
			{
				if ((this._Contraseña != value))
				{
					this.OnContraseñaChanging(value);
					this.SendPropertyChanging();
					this._Contraseña = value;
					this.SendPropertyChanged("Contraseña");
					this.OnContraseñaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Correo", DbType="VarChar(150)")]
		public string Correo
		{
			get
			{
				return this._Correo;
			}
			set
			{
				if ((this._Correo != value))
				{
					this.OnCorreoChanging(value);
					this.SendPropertyChanging();
					this._Correo = value;
					this.SendPropertyChanged("Correo");
					this.OnCorreoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaNacimiento", DbType="DateTime")]
		public System.Nullable<System.DateTime> FechaNacimiento
		{
			get
			{
				return this._FechaNacimiento;
			}
			set
			{
				if ((this._FechaNacimiento != value))
				{
					this.OnFechaNacimientoChanging(value);
					this.SendPropertyChanging();
					this._FechaNacimiento = value;
					this.SendPropertyChanged("FechaNacimiento");
					this.OnFechaNacimientoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaInicio", DbType="DateTime NOT NULL")]
		public System.DateTime FechaInicio
		{
			get
			{
				return this._FechaInicio;
			}
			set
			{
				if ((this._FechaInicio != value))
				{
					this.OnFechaInicioChanging(value);
					this.SendPropertyChanging();
					this._FechaInicio = value;
					this.SendPropertyChanged("FechaInicio");
					this.OnFechaInicioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Perfil", DbType="Int NOT NULL")]
		public int Perfil
		{
			get
			{
				return this._Perfil;
			}
			set
			{
				if ((this._Perfil != value))
				{
					if (this._Perfil1.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnPerfilChanging(value);
					this.SendPropertyChanging();
					this._Perfil = value;
					this.SendPropertyChanged("Perfil");
					this.OnPerfilChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_Residencia", DbType="Int")]
		public System.Nullable<int> ID_Residencia
		{
			get
			{
				return this._ID_Residencia;
			}
			set
			{
				if ((this._ID_Residencia != value))
				{
					if (this._Lugar.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnID_ResidenciaChanging(value);
					this.SendPropertyChanging();
					this._ID_Residencia = value;
					this.SendPropertyChanged("ID_Residencia");
					this.OnID_ResidenciaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EstadoCuenta", DbType="Bit NOT NULL")]
		public bool EstadoCuenta
		{
			get
			{
				return this._EstadoCuenta;
			}
			set
			{
				if ((this._EstadoCuenta != value))
				{
					this.OnEstadoCuentaChanging(value);
					this.SendPropertyChanging();
					this._EstadoCuenta = value;
					this.SendPropertyChanged("EstadoCuenta");
					this.OnEstadoCuentaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Perfil_Usuarios", Storage="_Perfil1", ThisKey="Perfil", OtherKey="ID", IsForeignKey=true)]
		public Perfil Perfil1
		{
			get
			{
				return this._Perfil1.Entity;
			}
			set
			{
				Perfil previousValue = this._Perfil1.Entity;
				if (((previousValue != value) 
							|| (this._Perfil1.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Perfil1.Entity = null;
						previousValue.Usuarios.Remove(this);
					}
					this._Perfil1.Entity = value;
					if ((value != null))
					{
						value.Usuarios.Add(this);
						this._Perfil = value.ID;
					}
					else
					{
						this._Perfil = default(int);
					}
					this.SendPropertyChanged("Perfil1");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Lugar_Usuarios", Storage="_Lugar", ThisKey="ID_Residencia", OtherKey="ID", IsForeignKey=true)]
		public Lugar Lugar
		{
			get
			{
				return this._Lugar.Entity;
			}
			set
			{
				Lugar previousValue = this._Lugar.Entity;
				if (((previousValue != value) 
							|| (this._Lugar.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Lugar.Entity = null;
						previousValue.Usuarios.Remove(this);
					}
					this._Lugar.Entity = value;
					if ((value != null))
					{
						value.Usuarios.Add(this);
						this._ID_Residencia = value.ID;
					}
					else
					{
						this._ID_Residencia = default(Nullable<int>);
					}
					this.SendPropertyChanged("Lugar");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.PuntuacionUsuario")]
	public partial class PuntuacionUsuario
	{
		
		private string _Nick_Usuario;
		
		private int _ID_Juego;
		
		private int _ID_Puntuacion;
		
		public PuntuacionUsuario()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nick_Usuario", DbType="VarChar(30) NOT NULL", CanBeNull=false)]
		public string Nick_Usuario
		{
			get
			{
				return this._Nick_Usuario;
			}
			set
			{
				if ((this._Nick_Usuario != value))
				{
					this._Nick_Usuario = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_Juego", DbType="Int NOT NULL")]
		public int ID_Juego
		{
			get
			{
				return this._ID_Juego;
			}
			set
			{
				if ((this._ID_Juego != value))
				{
					this._ID_Juego = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_Puntuacion", DbType="Int NOT NULL")]
		public int ID_Puntuacion
		{
			get
			{
				return this._ID_Puntuacion;
			}
			set
			{
				if ((this._ID_Puntuacion != value))
				{
					this._ID_Puntuacion = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Puntuaciones")]
	public partial class Puntuaciones : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private int _Puntuacion;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnPuntuacionChanging(int value);
    partial void OnPuntuacionChanged();
    #endregion
		
		public Puntuaciones()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Puntuacion", DbType="Int NOT NULL")]
		public int Puntuacion
		{
			get
			{
				return this._Puntuacion;
			}
			set
			{
				if ((this._Puntuacion != value))
				{
					this.OnPuntuacionChanging(value);
					this.SendPropertyChanging();
					this._Puntuacion = value;
					this.SendPropertyChanged("Puntuacion");
					this.OnPuntuacionChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Perfil")]
	public partial class Perfil : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private string _Tipo;
		
		private EntitySet<Usuarios> _Usuarios;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnTipoChanging(string value);
    partial void OnTipoChanged();
    #endregion
		
		public Perfil()
		{
			this._Usuarios = new EntitySet<Usuarios>(new Action<Usuarios>(this.attach_Usuarios), new Action<Usuarios>(this.detach_Usuarios));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tipo", DbType="VarChar(30) NOT NULL", CanBeNull=false)]
		public string Tipo
		{
			get
			{
				return this._Tipo;
			}
			set
			{
				if ((this._Tipo != value))
				{
					this.OnTipoChanging(value);
					this.SendPropertyChanging();
					this._Tipo = value;
					this.SendPropertyChanged("Tipo");
					this.OnTipoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Perfil_Usuarios", Storage="_Usuarios", ThisKey="ID", OtherKey="Perfil")]
		public EntitySet<Usuarios> Usuarios
		{
			get
			{
				return this._Usuarios;
			}
			set
			{
				this._Usuarios.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Usuarios(Usuarios entity)
		{
			this.SendPropertyChanging();
			entity.Perfil1 = this;
		}
		
		private void detach_Usuarios(Usuarios entity)
		{
			this.SendPropertyChanging();
			entity.Perfil1 = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Lugar")]
	public partial class Lugar : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private string _Comunidad;
		
		private string _Provincia;
		
		private EntitySet<Usuarios> _Usuarios;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnComunidadChanging(string value);
    partial void OnComunidadChanged();
    partial void OnProvinciaChanging(string value);
    partial void OnProvinciaChanged();
    #endregion
		
		public Lugar()
		{
			this._Usuarios = new EntitySet<Usuarios>(new Action<Usuarios>(this.attach_Usuarios), new Action<Usuarios>(this.detach_Usuarios));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Comunidad", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string Comunidad
		{
			get
			{
				return this._Comunidad;
			}
			set
			{
				if ((this._Comunidad != value))
				{
					this.OnComunidadChanging(value);
					this.SendPropertyChanging();
					this._Comunidad = value;
					this.SendPropertyChanged("Comunidad");
					this.OnComunidadChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Provincia", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string Provincia
		{
			get
			{
				return this._Provincia;
			}
			set
			{
				if ((this._Provincia != value))
				{
					this.OnProvinciaChanging(value);
					this.SendPropertyChanging();
					this._Provincia = value;
					this.SendPropertyChanged("Provincia");
					this.OnProvinciaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Lugar_Usuarios", Storage="_Usuarios", ThisKey="ID", OtherKey="ID_Residencia")]
		public EntitySet<Usuarios> Usuarios
		{
			get
			{
				return this._Usuarios;
			}
			set
			{
				this._Usuarios.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Usuarios(Usuarios entity)
		{
			this.SendPropertyChanging();
			entity.Lugar = this;
		}
		
		private void detach_Usuarios(Usuarios entity)
		{
			this.SendPropertyChanging();
			entity.Lugar = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Juegos")]
	public partial class Juegos : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private string _NombreJuego;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnNombreJuegoChanging(string value);
    partial void OnNombreJuegoChanged();
    #endregion
		
		public Juegos()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NombreJuego", DbType="VarChar(60) NOT NULL", CanBeNull=false)]
		public string NombreJuego
		{
			get
			{
				return this._NombreJuego;
			}
			set
			{
				if ((this._NombreJuego != value))
				{
					this.OnNombreJuegoChanging(value);
					this.SendPropertyChanging();
					this._NombreJuego = value;
					this.SendPropertyChanged("NombreJuego");
					this.OnNombreJuegoChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.seguidores")]
	public partial class seguidores
	{
		
		private string _NickUsuarioPrincipal;
		
		private string _NickUsuarioSeguidor;
		
		private System.Nullable<int> _NumerodeSeguidor;
		
		public seguidores()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NickUsuarioPrincipal", DbType="VarChar(30)")]
		public string NickUsuarioPrincipal
		{
			get
			{
				return this._NickUsuarioPrincipal;
			}
			set
			{
				if ((this._NickUsuarioPrincipal != value))
				{
					this._NickUsuarioPrincipal = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NickUsuarioSeguidor", DbType="VarChar(30)")]
		public string NickUsuarioSeguidor
		{
			get
			{
				return this._NickUsuarioSeguidor;
			}
			set
			{
				if ((this._NickUsuarioSeguidor != value))
				{
					this._NickUsuarioSeguidor = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NumerodeSeguidor", DbType="Int")]
		public System.Nullable<int> NumerodeSeguidor
		{
			get
			{
				return this._NumerodeSeguidor;
			}
			set
			{
				if ((this._NumerodeSeguidor != value))
				{
					this._NumerodeSeguidor = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
